# Generated by Django 4.1.2 on 2022-10-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up', models.CharField(max_length=50)),
                ('destiny', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=20)),
                ('observations', models.CharField(max_length=100)),
                ('passengers', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('comments', models.CharField(max_length=50)),
                ('stars', models.IntegerField(default=5)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
