# Generated by Django 4.1.2 on 2022-10-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('comments', models.CharField(max_length=50)),
                ('stars', models.IntegerField(default=5)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
